### ISSUE TITLE
Tela - Escritorios

### ISSUE THREAD

**Issue by felipe199903** [STARTUPS-VP-2018-1/rentoffice#8]
- Fazer alteração no layout,

- Ligar ela com o usuário: Locatario, (seja possível ele verificar quais estão disponíveis após fazer o login)

**Comment by brubstrevisann** [comment]
[RentOffice.zip](https://github.com/STARTUPS-VP-2018-1/rentoffice/files/2052144/RentOffice.zip)
 
Alteração no layout da tela Escritorios
